mydj/myProj/engine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^regist/$',views.regist,name='regist'),
	url(r'^welcome/$',views.welcome,name='welcome'),
	url(r'^user_password/$',views.user_password,name='user_password'),
	url(r'^information/$',views.information,name='information'),
	url(r'^course_list/$',views.course_list,name='course_list'),
	url(r'^t_index/$', views.my_course, name='my_course'),
	url(r'^test/$', views.test, name='test'),
    url(r'^upload/$',views.upload,name='upload'),
]

mydj/myProj/myProj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',include('engine.urls',namespace='engine')),
    url(r'^t_index/', include('tmanage.urls', namespace='tmanage')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mydj/myProj/tmanage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.t_index,name='t_index'),
	url(r'^t_login/$', views.t_login, name='t_login'),
	url(r'^t_logout/$', views.t_logout, name='t_logout'),
]

mydj/myProj/templates/course_list.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="{% static "js/html5shiv.js" %}"></script>
<script type="text/javascript" src="{% static "js/respond.min.js" %}"></script>
<![endif]-->
    <link rel="stylesheet" type="text/css" href="{% static "css/ui.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/admin.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/iconfont.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "skin/default/skin.css" %}" id="skin" />
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
<!--[if IE 6]>
<script type="text/javascript" src="{% static "js/DD_belatedPNG_0.0.8a-min.js" %}" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>选课查询</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 选课管理 <span class="c-gray en">&gt;</span> 课程列表 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
		{% if messages %}
                {% for message in messages %}
               <h4><font color="red"> <p align="center"  {% if message.tags %} class="{{ message.tags }}" {% endif %} style="padding: 10px">{{ message }}</p></font></h4>
                {% endfor %}{% endif %}
 <span class="r">共有数据：<strong>{{course_number}}</strong> 条</span> </div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-bg table-hover table-sort">
			<thead>
				<tr class="text-c">
					<th width="80">课程编号</th>
					<th width="100">课程名称</th>
					<th width="300">课程简介</th>
					<th width="100">授课教师</th>
					<th width="100">上课人数</th>
					<th width="150">上课时间</th>
					<th width="60">发布状态</th>
					<th width="200">操作</th>
				</tr>
			</thead>
				{% for key,value in courses_list.items %}
					<tbody class="{% cycle 'altrow' '' %}">
						<tr class="text-c">
							<form method='post' enctype="multipart/form-data" onsubmit="return user_input()"  >
								{% csrf_token %}
							<td>{{value.courseid}}</td>
							<td>{{value.coursename}}</td>
							<td>{{value.courseinfo}}</td>
							<td>{% for t in teacher %}
									{% ifequal t.pk value.teacherid.pk %}
								<h5>{{t.teachername}}</h5>
									{% endifequal %}
								{% endfor %}</td>
								<td class="text-c">
									{% for key1,value1 in course_num_list.items %}
										{% ifequal key1 key %}
											{{value1}}
										{% endifequal %}
									{% endfor %}
									/
										{{value.coursenum}}
								</td>
							<td>{{value.coursetime}}</td>
							<td class="td-status"><span class="label label-success radius">已发布</span></td>
							<td class="td-manage">
								<input type="submit"  name="{{value.coursename}}" style="display:none" value="{{value.coursename}}"> </input>
								<input type="image"  name="{{value.coursename}}" src="{% static "img/xuanke.png" %}" style="text-decoration:none" value="{{value.coursename}}"></input>
								<input type="image"  name="{{value.coursename}}" src="{% static "img/tuixuan.png" %}" style="text-decoration:none" value="{{value.coursename}}"></input>
							</td>
							</form>
						</tr>
					</tbody>
				{% endfor %}
		</table>
	</div>
</div>

<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "jquery/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/layer.js" %}"></script>
<script type="text/javascript" src="{% static "js/ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/admin.js" %}"></script>
<!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="lib/My97DatePicker/4.8/WdatePicker.js"></script> 
<script type="text/javascript" src="lib/datatables/1.10.0/jquery.dataTables.min.js"></script> 
<script type="text/javascript" src="lib/laypage/1.2/laypage.js"></script>

</body>
</html>

mydj/myProj/templates/index.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="/favicon.ico" >
<link rel="Shortcut Icon" href="/favicon.ico" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{% static "css/ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
<title>Management</title>
</head>
<body>
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl"> <a class="logo navbar-logo f-l mr-10 hidden-xs">Management System</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href="/aboutHui.shtml">H-ui</a>
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">0.9β</span>
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
			<nav class="nav navbar-nav">
				<ul class="cl">

			</ul>
		</nav>
			<nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
				<ul class="cl">
					<li class="dropDown dropDown_hover">
						<a href="#" class="dropDown_A">{{user.realname}}<i class="Hui-iconfont">&#xe6d5;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="">个人信息</a></li>
							<li><a href="{% url 'engine:logout'%}">退出</a></li>
					</ul>
				</li>
					<li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
							<li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
							<li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
							<li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
							<li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
							<li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
</header>
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">
		<dl id="menu-article">
			<dt><i class="Hui-iconfont">&#xe616;</i> 用户管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:user_password'%}" data-title="密码修改" href="javascript:void(0)">密码修改</a></li>
                    <li><a data-href="{% url 'engine:information'%}" data-title="基本信息" href="javascript:void(0)">基本信息</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-picture">
			<dt><i class="Hui-iconfont">&#xe613;</i> 选课管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:course_list'%}" data-title="查询选课" href="javascript:void(0)">查询选课</a></li>
					<li><a data-href="{% url 'engine:my_course'%}" data-title="我的课程和成绩" href="javascript:void(0)">我的课程和成绩</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-member">
			<dt><i class="Hui-iconfont">&#xe62d;</i> 提交作业<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:upload'%}" data-title="上传文件" href="javascript:void(0)">上传文件</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe62e;</i> 系统管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="system-base.html" data-title="系统设置" href="javascript:void(0)">系统设置</a></li>
			</ul>
		</dd>
	</dl>
</div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
	<div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
		<div class="Hui-tabNav-wp">
			<ul id="min_title_list" class="acrossTab cl">
				<li class="active">
					<span title="主页" data-href="{% url 'engine:welcome'%}">主页</span>
					<em></em></li>
		</ul>
	</div>
		<div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
</div>
	<div id="iframe_box" class="Hui-article">
		<div class="show_iframe">
			<div style="display:none" class="loading"></div>
			<iframe scrolling="yes" frameborder="0" src="{% url 'engine:welcome'%}"></iframe>
	</div>
</div>
</section>

<div class="contextMenu" id="Huiadminmenu">
	<ul>
		<li id="closethis">关闭当前 </li>
		<li id="closeall">关闭全部 </li>
</ul>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "jquery/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/layer.js" %}"></script>
<script type="text/javascript" src="{% static "js/ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/admin.js" %}"></script>
<!--/_footer 作为公共模版分离出去-->


<!--/此乃百度统计代码，请自行删除-->
</body>
</html>

mydj/myProj/templates/login.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static "css/Login_style.css" %}" />
    <script type="text/javascript" src="{% static "js/Login_javascript.js" %}"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login</title>
</head>

<body>
    <h1 align="center">
        <font color="white">Student Log in</font>
    </h1>
    <div class="login_frame"></div>
    <div class="LoginWindow">
        <div>

            <form method='post' enctype="multipart/form-data" onsubmit="return user_input()" class="login">
                {% csrf_token %}
                <p><label for="username">username:{{uf.username}}</label></p>
                <p><label style="margin-left:3px; for="password">password:{{uf.password}}</label></p>
                <!--{{uf.as_p}}-->
                <div style="text-align:justify;">
                    <input type="submit" id="Login" value="Log in" style="border-radius:20px;" />

                    <a href="{% url 'engine:regist'%}">Sign Up</a>
                    <a href="{% url 'tmanage:t_login'%}">Teacher Login</a>
                </div>
            </form>

        </div>
    </div>
                    {% if messages %}
                {% for message in messages %}
               <h3><font color="white"> <p align="center"  {% if message.tags %} class="{{ message.tags }}" {% endif %} style="padding: 10px">{{ message }}</p></font></h3>
                {% endfor %}{% endif %}
</body>

</html>

mydj/myProj/templates/regist.html
<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Regist</title>
</head>

<body>
    <h1>Sign up with</h1>
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{uf.as_p}}
        <input type="submit" value="ok" />
    </form>
    <br>
    <a href="{% url 'engine:login'%}">Log in</a>
</body>
</html>

mydj/myProj/templates/t_index.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="/favicon.ico" >
<link rel="Shortcut Icon" href="/favicon.ico" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{% static "css/ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
<title>Management</title>
</head>
<body>
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl"> <a class="logo navbar-logo f-l mr-10 hidden-xs">Management System</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href="/aboutHui.shtml">H-ui</a>
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">0.9β</span>
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
			<nav class="nav navbar-nav">
				<ul class="cl">

			</ul>
		</nav>
			<nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
				<ul class="cl">
					<li class="dropDown dropDown_hover">
						<a href="#" class="dropDown_A">{{teacher.teachername}}<i class="Hui-iconfont">&#xe6d5;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="">个人信息</a></li>
							<li><a href="{% url 'tmanage:t_logout'%}">退出</a></li>
					</ul>
				</li>
					<li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
							<li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
							<li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
							<li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
							<li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
							<li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
</header>
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">
		<dl id="menu-article">
			<dt><i class="Hui-iconfont">&#xe616;</i> 用户管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:user_password'%}" data-title="密码修改" href="javascript:void(0)">密码修改</a></li>
                    <li><a data-href="{% url 'engine:information'%}" data-title="基本信息" href="javascript:void(0)">基本信息</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-picture">
			<dt><i class="Hui-iconfont">&#xe613;</i> 选课管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:course_list'%}" data-title="查询选课" href="javascript:void(0)">查询选课</a></li>
					<li><a data-href="{% url 'engine:my_course'%}" data-title="我的课程和成绩" href="javascript:void(0)">我的课程和成绩</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-member">
			<dt><i class="Hui-iconfont">&#xe62d;</i> 提交作业<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'engine:upload'%}" data-title="上传文件" href="javascript:void(0)">上传文件</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe62e;</i> 系统管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="system-base.html" data-title="系统设置" href="javascript:void(0)">系统设置</a></li>
			</ul>
		</dd>
	</dl>
</div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
	<div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
		<div class="Hui-tabNav-wp">
			<ul id="min_title_list" class="acrossTab cl">
				<li class="active">
					<span title="主页" data-href="{% url 'engine:welcome'%}">主页</span>
					<em></em></li>
		</ul>
	</div>
		<div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
</div>
	<div id="iframe_box" class="Hui-article">
		<div class="show_iframe">
			<div style="display:none" class="loading"></div>
			<iframe scrolling="yes" frameborder="0" src="{% url 'engine:welcome'%}"></iframe>
	</div>
</div>
</section>

<div class="contextMenu" id="Huiadminmenu">
	<ul>
		<li id="closethis">关闭当前 </li>
		<li id="closeall">关闭全部 </li>
</ul>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "jquery/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/layer.js" %}"></script>
<script type="text/javascript" src="{% static "js/ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/admin.js" %}"></script>
<!--/_footer 作为公共模版分离出去-->


<!--/此乃百度统计代码，请自行删除-->
</body>
</html>

mydj/myProj/templates/t_login.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static "css/Login_style.css" %}" />
    <script type="text/javascript" src="{% static "js/Login_javascript.js" %}"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login</title>
</head>

<body>
    <h1 align="center">
        <font color="white">Teacher Log in</font>
    </h1>
    <div class="login_frame"></div>
    <div class="LoginWindow">
        <div>
            <form method='post' enctype="multipart/form-data" onsubmit="return user_input()" class="login">
                {% csrf_token %}
                <p><label for="teacherid">teacherid:{{tf.teacherid}}</label></p>
                <p><label style="margin-right:9px; for="password">password:{{tf.password}}</label></p>
                <!--{{uf.as_p}}-->
                <div style="text-align:justify;">
                    <input type="submit" value="Log in" style="border-radius:20px;" />

                    <a href="{% url 'engine:login'%}">Student Login</a>
                </div>
            </form>

        </div>
    </div>
</body>

</html>

mydj/myProj/templates/teacher_login.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static "css/Login_style.css" %}" />
    <script type="text/javascript" src="{% static "js/Login_javascript.js" %}"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login</title>
</head>

<body>
    <h1 align="center">
        <font color="white">Teacher Log in</font>
    </h1>
    <div class="login_frame"></div>
    <div class="LoginWindow">
        <div>
            <form method='post' enctype="multipart/form-data" onsubmit="return user_input()" class="login">
                {% csrf_token %}
                <p><label for="teacherid">teacherid:{{tf.teacherid}}</label></p>
                <p><label style="margin-right:9px; for="password">password:{{tf.password}}</label></p>
                <!--{{uf.as_p}}-->
                <div style="text-align:justify;">
                    <input type="submit" value="Log in" style="border-radius:20px;" />

                    <a href="{% url 'engine:login'%}">Student Login</a>
                </div>
            </form>

        </div>
    </div>
</body>

</html>

mydj/myProj/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for key,value in dicts.items %}
  <tr class="{% cycle 'altrow' '' %}">
    <td>{{ key }}</td>
    <td>{{ value.coursename }}</td>
      <br/>
  </tr>
{% endfor %}
</body>
</html>

mydj/myProj/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
</head>
<body>

</body>
</html>

mydj/myProj/templates/user_information.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="{% static "css/ui.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/admin.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/iconfont.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "skin/default/skin.css" %}" id="skin" />
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
    <title>User Information</title>
</head>

<body>
    <h1>User Information</h1>

</body>
</html>